### PR TITLE
Fix crash

### PR DESCRIPTION
**Pull request by eliyya**
* sudden crash caused by volume [pull request](https://github.com/eliyya/ts-yasha/pull/1)
* Updated clientVersion & fixed Android input error that caused 403 Error [pull request](https://github.com/eliyya/ts-yasha/pull/2)

Both errors checked

Thanks to [Rubén Ortiz](https://github.com/rubenOrtz)

### CODE REVIEW

**Comment by eliyya** [comment]
There are a lot of commits but they are only to synchronize the changes, only the last 2 are the fixes

**Comment by davidzeng0** [comment]
Hmm... I've never experienced a crash from the normalize_volume option. Is this from a custom-implemented track? Because iirc (and even in index.d.ts), the volume property is non-nullable.

Other than that, LGTM

**Comment by davidzeng0** [comment]
Would you mind rebasing for me and using cherry-pick rather than merging?

**Comment by eliyya** [comment]
I saw it too late, sorry

**Pull request merged**
