### PR TITLE
Updated Youtube.js documentation to include example cookie string

### PR DESCRIPTION
**Pull request by andrew101sanders**
It took me a while to figure out how to format the string so Youtube would accept it, so I added an example string to the documentation.

### CODE REVIEW

**Comment by davidzeng0** [comment]
I'll come back to this PR when I have energy to. Though I do recall reading some guide on how to locate the cookie from Walkysts's lavaplayer-fork repository. Can't remember where it is though

**Comment by davidzeng0** [comment]
I think if you can make a guide on how to find the cookie (in devtools) it would help a lot more than just saying what the contents of the cookie should include. I think that would better satisfy your intentions with this pull request. I have other things I have to work on so I'll leave this up to you :)

**Comment by davidzeng0** [comment]
Also I'm not quite sure what you meant by "format the string" because I just copy and paste the cookie from a fetch request

**Comment by andrew101sanders** [comment]
>Also I'm not quite sure what you meant by "format the string" because I just copy and paste the cookie from a fetch request

Oh, interesting! Do you just copy the entire cookie value? I just tried to find the "minimum viable string" so youtube would let you play age-restricted videos and Youtube.js would correctly parse it. I didn't realize the code was written with the intention of using the copied string from a fetch request.

I've updated the comments to give short instructions on how to access the cookie values in a browser. I would have created a simple js singer liner to get the values in the correct format, but __Secure-3PSID is httpOnly.

**Comment by davidzeng0** [comment]
I think it would be good to make clear that the two values can be different.

I don't usually put docs in my code so I removed the comment from there, hope you don't mind.

**Review by andrew101sanders — COMMENTED** [review]
Didn't see the changed file. Commiting.

**Comment by davidzeng0** [comment]
What do you mean "Committing"? If you're fine with the changes I can merge right away, just let me know :)

**Comment by andrew101sanders** [comment]
Oh, I derped, yeah go ahead lol

**Pull request merged**
